#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="Sachin Arunkumar"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=preemptive signals(only pipe()functionality is implemented)
PROJECT_POINTS=70
